global:
  environment: dev
  namespace: dev
services:
  frontend-service:
    replicas: 2
    image:
      tag: e3132b2827a6605ab682a5422c40d2b4d2f46b3b
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
  core-api-service:
    replicas: 2
    image:
      tag: 8e460159a6c55caa014033a20fd67841df107b0c
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
    keyvault:
      secrets:
        - name: "dev-database-url"
          alias: "DATABASE_URL"
        - name: "dev-jwt-secret-key"
          alias: "JWT_SECRET_KEY"
        - name: "dev-internal-api-key"
          alias: "INTERNAL_API_KEY"
  alert-ingestion-service:
    replicas: 2
    image:
      tag: 240b2963b91fa8e6037c6163ffa9362510fd3f12
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
    keyvault:
      secrets:
        - name: "dev-database-url"
          alias: "DATABASE_URL"
        - name: "dev-internal-api-key"
          alias: "INTERNAL_API_KEY"
  ai-analysis-service:
    replicas: 2
    image:
      tag: 8319438a0be52e19ddee00006ff584db4dbf2de0
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
    keyvault:
      secrets:
        - name: "dev-database-url"
          alias: "DATABASE_URL"
        - name: "dev-internal-api-key"
          alias: "INTERNAL_API_KEY"
        - name: "dev-azure-foundry-api-key"
          alias: "AZURE_FOUNDRY_API_KEY"
  notification-service:
    replicas: 2
    image:
      tag: c470af9c1eff24bc6b30484e01ed2c70a0f04a33
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
    keyvault:
      secrets:
        - name: "dev-database-url"
          alias: "DATABASE_URL"
        - name: "dev-slack-webhook-url"
          alias: "SLACK_WEBHOOK_URL"
ingress:
  host: "dev.aasikdevops.website"
