global:
  environment: dev
  namespace: dev
services:
  frontend-service:
    replicas: 2
    image:
      tag: 0eb2061071487f1dd8a380575df6fcb48dd9a0cf
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
  core-api-service:
    replicas: 2
    image:
      tag: eb9e105f38f7321c5610fd1ba8c40bb406c45f07
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
  alert-ingestion-service:
    replicas: 2
    image:
      tag: 4e7ce2e23c70e30f2d8963687cd4eecf290f955e
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
  ai-analysis-service:
    replicas: 2
    image:
      tag: 161d0ab073170f434c45996cc5560069cce7af42
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
  notification-service:
    replicas: 2
    image:
      tag: 732cd8fc801003dcf083e9c56d67511319e6d23a
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
