global:
  environment: prod
  namespace: prod
services:
  frontend-service:
    replicas: 3
    image:
      tag: frontend-service-v2.1.2
    autoscaling:
      minReplicas: 3
      maxReplicas: 10
  core-api-service:
    replicas: 3
    image:
      tag: core-api-service-v2.1.2
    autoscaling:
      minReplicas: 3
      maxReplicas: 10
    keyvault:
      secrets:
        - name: "prod-database-url"
          alias: "DATABASE_URL"
        - name: "prod-jwt-secret-key"
          alias: "JWT_SECRET_KEY"
        - name: "prod-internal-api-key"
          alias: "INTERNAL_API_KEY"
  alert-ingestion-service:
    replicas: 3
    image:
      tag: alert-ingestion-service-v2.1.2
    autoscaling:
      minReplicas: 3
      maxReplicas: 10
    keyvault:
      secrets:
        - name: "prod-database-url"
          alias: "DATABASE_URL"
        - name: "prod-internal-api-key"
          alias: "INTERNAL_API_KEY"
  ai-analysis-service:
    replicas: 3
    image:
      tag: ai-analysis-service-v2.1.2
    autoscaling:
      minReplicas: 3
      maxReplicas: 10
    keyvault:
      secrets:
        - name: "prod-database-url"
          alias: "DATABASE_URL"
        - name: "prod-internal-api-key"
          alias: "INTERNAL_API_KEY"
        - name: "prod-azure-foundry-api-key"
          alias: "AZURE_FOUNDRY_API_KEY"
  notification-service:
    replicas: 3
    image:
      tag: notification-service-v2.1.2
    autoscaling:
      minReplicas: 3
      maxReplicas: 10
    keyvault:
      secrets:
        - name: "prod-database-url"
          alias: "DATABASE_URL"
        - name: "prod-slack-webhook-url"
          alias: "SLACK_WEBHOOK_URL"
