global:
  environment: dev
  namespace: dev
services:
  frontend-service:
    replicas: 2
    image:
      tag: 0eb2061071487f1dd8a380575df6fcb48dd9a0cf
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
  core-api-service:
    replicas: 2
    image:
      tag: 940d1547d1f088c74709be035e1c82ba7e49c679
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
    keyvault:
      secrets:
        - name: "dev-database-url"
          alias: "DATABASE_URL"
        - name: "dev-jwt-secret-key"
          alias: "JWT_SECRET_KEY"
        - name: "dev-internal-api-key"
          alias: "INTERNAL_API_KEY"
  alert-ingestion-service:
    replicas: 2
    image:
      tag: fc0e90bd6d8c6b96b7bf970232738533163cee22
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
    keyvault:
      secrets:
        - name: "dev-database-url"
          alias: "DATABASE_URL"
        - name: "dev-internal-api-key"
          alias: "INTERNAL_API_KEY"
  ai-analysis-service:
    replicas: 2
    image:
      tag: 3020779866edabfe64e8be120f920c79c0a215b2
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
    keyvault:
      secrets:
        - name: "dev-database-url"
          alias: "DATABASE_URL"
        - name: "dev-internal-api-key"
          alias: "INTERNAL_API_KEY"
        - name: "dev-azure-foundry-api-key"
          alias: "AZURE_FOUNDRY_API_KEY"
  notification-service:
    replicas: 2
    image:
      tag: 5604d87c367f6fe45ef8a9425c0cf68fd66a3e54
    autoscaling:
      minReplicas: 2
      maxReplicas: 4
    keyvault:
      secrets:
        - name: "dev-database-url"
          alias: "DATABASE_URL"
        - name: "dev-slack-webhook-url"
          alias: "SLACK_WEBHOOK_URL"
