{{- range $serviceName, $service := .Values.services }}
{{- if and $service.enabled $service.keyvault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $.Release.Name }}-{{ $service.name }}-spc
  namespace: {{ $.Values.global.namespace | default $.Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ $service.serviceAccount.clientId | quote }}
    keyvaultName: {{ $.Values.global.keyVaultName | quote }}
    tenantId: {{ $.Values.global.tenantId | quote }}
    objects: |
      array:
        {{- range $secret := $service.keyvault.secrets }}
        - |
          objectName: {{ $secret.name }}
          objectType: secret
          objectAlias: {{ $secret.alias }}
        {{- end }}
  {{- if $service.keyvault.secrets }}
  secretObjects:
    - secretName: {{ $.Release.Name }}-{{ $service.name }}-secret
      type: Opaque
      data:
        {{- range $secret := $service.keyvault.secrets }}
        - objectName: {{ $secret.alias }}
          key: {{ $secret.alias }}
        {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
