{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Name }}-{{ $service.name }}-sa
  namespace: {{ $.Values.global.namespace | default $.Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ $service.serviceAccount.clientId | quote }}
  labels:
    app: {{ $service.name }}
    app.kubernetes.io/name: {{ $service.name }}
    app.kubernetes.io/component: {{ $service.component }}
    app.kubernetes.io/part-of: opsgpt
    environment: {{ $.Values.global.environment }}
    azure.workload.identity/use: "true"
---
{{- end }}
{{- end }}
